import { Events } from 'discord.js';
import { isThreadActive } from '../utils/threads.js';
import { generateAIResponse } from '../utils/ai.js';

export const name = Events.MessageCreate;

export async function execute(message) {
    if (message.author.bot) return;

    if (isThreadActive(message.channelId)) {
        await message.channel.sendTyping();

        try {
            const fetched = await message.channel.messages.fetch({ limit: 100 });
            const chronological = Array.from(fetched.values()).reverse();

            const contents = [];
            for (const msg of chronological) {
                if (msg.author.bot && msg.author.id !== message.client.user.id) continue;
                if (!msg.content) continue;

                const role = msg.author.id === message.client.user.id ? 'model' : 'user';
                const text = role === 'user' ? `${msg.author.username}: ${msg.content}` : msg.content;

                if (contents.length > 0 && contents[contents.length - 1].role === role) {
                    contents[contents.length - 1].parts[0].text += `\n${text}`;
                } else {
                    contents.push({ role, parts: [{ text }] });
                }
            }

            if (contents.length > 0 && contents[0].role === 'model') {
                contents.shift();
            }

            if (contents.length === 0) return;

            const response = await generateAIResponse(
                contents,
                'You are Renmade, a friendly, conversational AI assistant speaking in a dedicated chat thread. Maintain a natural, engaging, and friendly conversational flow. You must ONLY use natural, paragraph-based conversational language. Never use bullet points, numbered lists, markdown checklists, or structured grids; speak naturally as a human friend would in a casual chat. Aggressively reduce token usage by keeping responses short, direct, and highly concise without sacrificing helpfulness. Avoid verbose explanations or AI filler.',
                250,
                [{ googleSearch: {} }]
            );

            if (!response) {
                return await message.reply('No response was generated by the model.');
            }

            const truncated = response.length > 2000 ? response.substring(0, 1997) + '...' : response;
            await message.reply(truncated);
        } catch (error) {
            if (error.message === 'SAFETY_VIOLATION') {
                return await message.reply('Your message contains terms that violate our safety policies. Please keep conversations safe and constructive.');
            }
            console.error(error);
            await message.reply('Sorry, I encountered an error while processing your message.');
        }
    }
}
